### ISSUE TITLE
Option to escape \n

### ISSUE THREAD

**Issue by hrehfeld** [JelteF/PyLaTeX#116]
In Latex it's a big deal to have \n in say, tables. We need an option to escape \n with %\n:

    \begin{tabular}
    something

to

    \begin{tabular}%
    something

This should be provided for any command (as whether you need it depends on the enclosing comand)

**Comment by JelteF** [comment]
I understand the issue, but I'm not entirely sure how this could be implemented cleanly. 
For which `\n` characters should this be possible to make it useful?

**Comment by hrehfeld** [comment]
well, not 100%, but is it a problem to have it on every \n that the lib emits?

**Comment by JelteF** [comment]
Hmm, I guess that should not be an issue for most cases, but the main issue I see is the `begin_paragraph` settings. These emit new lines because they want to create a new paragraph. https://jeltef.github.io/PyLaTeX/current/pylatex/pylatex.base_classes.latex_object.html#pylatex.base_classes.latex_object.LatexObject.begin_paragraph

Do you see any solution for that?

**Comment by JelteF** [comment]
I just fixed this. Only the paragraph newlines are not escaped.
