### ISSUE TITLE
How to add "\" or "{" into a tex file?

### ISSUE THREAD

**Issue by xiuyanduan** [JelteF/PyLaTeX#128]
I am a newbie of `Python` and `LaTex`. Now I have designed a `.tex` file. Then I want use `PyLaTex` (version 1.0.0 )to generate this `.tex` file and compile it with `xelatex` .There are some questions confused me for a few days.I couldn't get answers by myself ,nor the search engine. Please help me, thanks a lot.

- How to set the documentclass with some variables? Such as
```tex
\documentclass[11pt,a4paper]{article}
```

-  How to add some text with `\` or `{}` into the `tex` file?  I tried `doc.packages.append` and `doc.append`, but both of them will change `\` to `\textbackslash{}` and change `{` to `\{` which make the `tex` compile fail. I added `r''` or `u''`  didn't work. I want to append some text into `tex` such as
```tex
\definecolor{ColorName}{RGB}{76,73,72}  
\setCJKmainfont{SimHei} 
\setCJKmonofont{KaiTi}  
\setmainfont{Times New Roman}
```
If I typed `doc.packages.append(r'\definecolor{ColorName}{RGB}{76,73,72}')` it will generate `\textbackslash{}definecolor\{ColorName\}\{RGB\}\{76,73,72\}`

- How to append `\vspace` and `\hspace` into a figure? To make the `tex` like
```tex
\begin{figure}[h!]
\vspace{17.634mm}\hspace*{54.314mm}
\includegraphics[width=10.3977cm]{title.jpg}
\end{figure}
```

- Where could I get more documents except [https://jeltef.github.io/PyLaTeX/latest/index.html](https://jeltef.github.io/PyLaTeX/latest/index.html)

Thanks a lot. `PyLaTex` helped me a lot , but I couldn't get enough documents.
Waiting for your reply.

**Comment by xiuyanduan** [comment]
I tried in `PyLaTex 0.8` . It works well.
When I typed `doc.preamble.append('\definecolor{ColorName}{RGB}{76,73,72}')` it generated `\definecolor{ColorName}{RGB}{76,73,72}`
But in `PyLaTex 1.0.0` it generated `\textbackslash{}definecolor\{ColorName\}\{RGB\}\{76,73,72\}` with same input.
Please tell me how to input `\` and `{}` in `PyLaTex 1.0.0`

**Comment by kriete** [comment]
Hey xiuyanduan,
I have a bit of experience using pylatex and just saw this issue, maybe I can help you. 

> How to set the documentclass with some variables? 

- You can define the document class by using the pylatex Options
`from pylatex.base_classes.command import Options`
and set the document class like this:
`doc.documentclass.options=Options('12pt', 'svgnames', 'final')`


> How to add some text with \ or {} into the tex file?

- I think your problem is that firstly python escapes the backslashes and pylatex also in some occurences. You can avoid this by following the basic example provided in the pylatex examples using the pylatex NoEscape function with the prefix r before your string.

See here e.g.: [basic example](https://jeltef.github.io/PyLaTeX/latest/examples/basic.html)
here it's used like this:

> doc.append(NoEscape(r'\maketitle'))

In your case I would suggest you use
`doc.preamble.append(NoEscape(r'\definecolor{ColorName}{RGB}{76,73,72}'))`

Note that you have to import the NoEscape definition first:
`from pylatex import NoEscape`


> How to append \vspace and \hspace into a figure?

- Using the python `with` command you are basically inside the figure environment and using `doc.append(NoEscape(r''))` should do the trick (I guess)

```
with doc.create(Figure(position='htbp')) as plot:
    doc.append(NoEscape(r''))
    plt.plot(x,y)
    plot.add_plot(width=NoEscape(r'1\textwidth'))
```

Hope that helps to solve your problem. Let us know how this works out for you.

By the way, if you don't do this already, you can let pylatex generate your pdf document by e.g. calling
doc.generate_pdf(extra_compiler_args='--xelatex')

Regards,
Andreas

**Comment by JelteF** [comment]
@kriete thanks for replying, your solutions should work. 
Some slight aditions.
Another option is to use a `Command` object, for the definecolor command instead of a raw string.
https://jeltef.github.io/PyLaTeX/latest/pylatex/pylatex.base_classes.command.html#pylatex.base_classes.command.Command

To set the options on the documentclass you can also pass in a `Command` object as the `documentclass` parameter for the `Document`. You can then set the options there. 

The vspace and hspace question should probably not be done by adding an empty string. I think you meant this: 
`doc.append(NoEscape(r'\vspace{17.634mm}\hspace*{54.314mm}'))`

Important to note for the xelatex solution is that this requires that `latexmk` is installed, which is highly advised as it compiles latex, biblatex and others as much as necessary. If you want to not use `latexmk` anyway you can simply use the `compiler` argument and set it to `xelatex`.

**Comment by JelteF** [comment]
I will close this as all of this should be possible, please reopen if issues occur.

**Comment by xiuyanduan** [comment]
@kriete Thanks a lot . I solved my questions by your reply.
@JelteF Appreciated for your explain and this wonderful PyLaTex. I should read the document again carefully. Thanks!
