### ISSUE TITLE
Repeated execution in jupyter notebook increases length of preamble?

### ISSUE THREAD

**Issue by michaelaye** [JelteF/PyLaTeX#145]
very mysteriously, everytime I run my pylatex code inside a notebook, the preamble grows by these 3 lines:

``` latex
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
```

This must be some caching issue, as I don't see any related dot files and deleting the intermediate tex file (or using `clean_tex=True`) does not prevent this from happening. Only a reset of the notebook will create a lean preamble again.

Versions:
- pylatex 1.0.0 (via pip)
- jupyter notebook server 4.2.3
- Python 3.5.2
- IPython 5.1.0 

(up-to-date conda python 3 install)

**Comment by michaelaye** [comment]
Apparently this only happens if I return a Document() object from a function and store that in a variable. This must be caused by some of the IPython/Jupyter caching, I guess?

**Comment by JelteF** [comment]
Can you try installing the git version of pylatex, it could be that this bug is fixed there.

**Comment by mbdevpl** [comment]
An ugly workaround for this issue is by using `doc.packages.clear()` after constructing a `doc = Document(...)` - this gets rid of all packages, including the duplicates. However when I do `doc = Document(...)` again, all the duplicates come back.

In any case, this is resolved in the version from the repo. Could you update the PyPI package?

**Comment by JelteF** [comment]
I just released a new version yesterday. So this should be fixed on pypi now.
