### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by Starow** [JelteF/PyLaTeX#20]
Hello,
Thanks to have merged the pull request 3 days ago.
Could you also push this master version on pip?
`pip show` display version 0.5 of PyLateX I don't know if this one is the current or not :)
Thanks in advance !

**Comment by JelteF** [comment]
I haven't put it up on pip yet, because quite a bit changed and I have to change some stuff in the README and such. I plan on realeasing within the next week. If you need it really quick you can just clone the repo and call `python setup.py install`. This will work for Python 3. 

For Python 2 you will need to download and install awkwardduet, and then run the convert_to_py2.sh script. And then you can install it using the same method as for python 3.

**Comment by JelteF** [comment]
I just released a new version on pip.

**Comment by Starow** [comment]
Yay perfect ! thanks a lot !

**Comment by sebastianhaas** [comment]
You might want to create a corresponding tag in the repository too. :)

**Comment by JelteF** [comment]
Done
