### ISSUE TITLE
What's the point of `real_data` attribute in `BaseLaTeXContainer`?

### ISSUE THREAD

**Issue by Vayel** [JelteF/PyLaTeX#24]
Hello!

I don't understand what the `real_data` attribute is for in the `BaseLaTeXContainer` class. I would code the `__init__` method like below but I don't know if `real_data` needs to be `None`.

```python
def __init__(self, data=[], packages=None):
    self.data = data
    self.real_data = data  # Always the data of this instance

    super().__init__(packages=packages)
```

Thanks!

**Comment by JelteF** [comment]
Within a with statement data becomes the data of the child of the element, while `real_data` always is the data of the actual instance.
a simple example:
```python
doc = Document()
doc.append('This is the main document')
with doc.create(Section('One level)) as section:
    doc.append('This is the section')
    doc.real_data[0] # 'This is the main document'
    doc.data[0] # 'This is the section'
    doc[0] # 'This is the section'
    section[0] # 'This is the section'
```

**Comment by Vayel** [comment]
Ok thanks!

So the code above works, doesn't it?

**Comment by JelteF** [comment]
First of all, if you are trying to subclass `BaseLaTexContainer` and you want to let your `__init__` do nothing different from its `__init__` you shouldn't define one, since it will just use the `__init__` from `BaseLaTexContainer`. If you need to do something yourself as well, you should just do that and pass data and packages to `super().__init__(data=data, packages=packages). You could even leave packages out if you don't need it.

Lastly, never use a list as a default value, since it is mutable and it causes weird and unwanted behaviour. See: https://stackoverflow.com/questions/1132941/least-astonishment-in-python-the-mutable-default-argument

What are you trying to do? I could probably help you a bit.
