### ISSUE TITLE
Bounding Box pixels of each component in pdf

### ISSUE THREAD

**Issue by ChiragSoni95** [JelteF/PyLaTeX#240]
Can we get pixel co-ordinates (xmin,ymin,xmax,ymax) for each components that we place in the pdf?
Like images, table images, and paragraphs?

**Comment by ChiragSoni95** [comment]
Exactly!! I get your point, but my actual motive here is to create a synthetic documents dataset. If even somehow I create thousands of documents, there is no way to annotate them. Can you suggest some solution?
I took this approach in the first place, because we know while placing components in the pdf(but as pointed by you, latex does that on its own).
Is there any other way to create a large synthetic document dataset along with annotations?

**Comment by JelteF** [comment]
Getting the position from created elements is definitly out of scope for PyLaTeX. However, I think you can achieve what you want by using one of the annotation packages that exist for LaTeX. One example of this is this package: https://tex.stackexchange.com/a/268275, but there might be better ones for your use case, so I recommend googling yourself a bit. 

As a general rule, look for solutions to your problems that also work in regular LaTeX, because PyLaTeX is only meant to make generating that LaTeX code easy.
