### ISSUE TITLE
how to reference a label in a valid way? 

### ISSUE THREAD

**Issue by yangdaweihit** [JelteF/PyLaTeX#306]
When it is needed to reference a label of a figure, for example:
```
    with doc.create(Figure(position='htpb')) as logo:
        logo_file = os.path.join(os.path.dirname(__file__), 'logo.png')
        logo.append(Label('fig:logo'))
        logo.add_image(logo_file, width=NoEscape(r'0.2\textwidth'))
        logo.add_caption('logo of hit')
```
how to do it in a valid way? It occurs to me for 2 questions:

1. When I try to get the `\ref{fig:logo}`， only the following is correct:
```
doc.append(`as the figure`)
doc.append(`Ref(`fig:logo`))
doc.append(`shows...`)
```
While the might favorable form is:
```
doc.append(`as the figure` + Ref(`fig:logo`).dumps() + `shows...`)
```
which got 
```
as the figure \textbackslash{}ref\{fig:logo\} shows ...
```

2. Once I got the valid `tex` file, I need to compile it at least twice so that the pdf with referenced number of figure can be generated. How to use `genereate_pdf` to accomplish this pdf?

**Comment by JelteF** [comment]
READ THE DOCS NEXT TIME!
1. You can use `NoEscape` if you really want, like mentioned in the first section of the docs: https://jeltef.github.io/PyLaTeX/latest/usage.html#unescaping-strings
2. Literally in the FAQ: https://jeltef.github.io/PyLaTeX/latest/faq.html

**Comment by yangdaweihit** [comment]
I'm not sure the following code is your meaning:
```
    ref_tex = Ref(Marker('logo', prefix='fig'))
    ref_tex.escape = False
    doc.append('as the figure' + ref_tex.dumps())
```

or 

```
doc.append('as the figure' +  Ref(Marker('logo', prefix='fig')).dumps())
```

It produces such result:
```
as the figure\textbackslash{}ref\{fig:logo\}%

```

**Comment by JelteF** [comment]
I now understand better what you mean, and also see that you already found `NoEscape`. But in what you want it will not help you indeed. In your comment on anether issue I see that you are using `xelatex`. So let me try to answer your questions better now.

1. You can use `doc.extend` to add a list of multiple items to the doc in a single call. All latex containers are simply lists underneath, because they inherit  from `UserList`.
```python
doc.extend(['as the figure', Ref('fig:logo'), 'shows...'])
```
2. If you want to combine `xelatex` (for Chinese) and `latexmk` (for compiling multiple times) you should be able to use this:
```python
doc.generate_pdf(compiler='latexmk', compiler_args=['-xelatex'])
```

**Comment by yangdaweihit** [comment]
It's so kind that you have noticed my comment in another issue. Thanks for your nice answer.
