### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Starow** [JelteF/PyLaTeX#31]
Hello,
I read your introduction/presentation and you're saying:
"Everything else you want you can still add to the document by adding LaTeX formatted strings to the container class you want it to be in."
Could you provide an example ?

I would like to add a Tittle page at the very beggining of a document created with PyLaTeX.
Is it possible to add directly "raw" latex command such as \newpage or a group of these kind of lines with PyLaTeX ? 
Thank you in advance! :)

**Comment by JelteF** [comment]
Yes, any object inherits from one of the container baseclasses can also contain "raw" latex strings.
You can just do:

```python
doc = Document()
doc.append(r'\newpage')
doc.append('This is on a new page')
```
In some cases it might be easier to use the Command class. This is mostly the case when your commands need arguments that aren't hard coded.
If you need a specific environment (like enumerate wiht a `begin` and `end` command) it might be easiest to inherit LatexNamedContainer, since that does that for you and you can use the `with` syntax that way.

**Comment by Starow** [comment]
Thank you for these infos and the fast reply!
I passed everything inside some r'text' strings and it works :)

**Comment by JelteF** [comment]
No problem. BTW the `r` before `r'text'` is just so you don't have to escape all the backslashes its something that is built in to python.

**Comment by LydiaF** [comment]
Thank you for this info :)

**Comment by jdonkervliet** [comment]
Note that this no longer works. You should use wrap your raw latex in `NoEscape` or use the `Command` class in case you want to insert a command.
