### ISSUE TITLE
graphicx package not being imported

### ISSUE THREAD

**Issue by petaflot** [JelteF/PyLaTeX#331]
steps to reproduce:

1) take example from https://jeltef.github.io/PyLaTeX/current/examples/complex_report.html
2) replace PNG pictures by a cute kitten
3) comment out Header image code
4) add _cheque_ images not to _doc_, but to _customer_ or _branch_ (relevant section of the code must be moved around and somewhat indented)
5) notice how ```latex
\usepackage{graphicx}%``` is now missing from the latex output : the cute kittens are gone.

**Comment by JelteF** [comment]
It's not clear to me what the problem is. You replaced the pictures in the header with a kitten. and then commented that code out. Then it makes sense that the kittens are gone, because you commented them out. 

In any case, without a clear error and code I cannot help you. Feel free to update the issue with more detail.

**Comment by petaflot** [comment]
I didn't comment _these_ kitten out ; just the kitten in the header (which caused \usepackage{grpahicx}" to be inserted in the tex file.

_these_ kittens, without the the image in the header, are shown as text (like [width=50px],path=... or sth similar ; it's hard to see because the text that is displayed were there should be images is overlapping and made unreadable

**Comment by JelteF** [comment]
Like I said your description of the issue is not clear enough for me to
provide help. There's no code, and no resulting tex file. Could you please
provide those?
