### ISSUE TITLE
Deleting files does not work on Windows

### ISSUE THREAD

**Issue by winogradoff** [JelteF/PyLaTeX#56]
Deleting files does not work on Windows.
Because you're using linux command "rm'.
It is better to use os.remove:
https://docs.python.org/2/library/os.html#os.remove

**Comment by jrast** [comment]
I've changed the file deletion in generate_pdf() to this:
```python
    if clean:
        for ext in ['.aux', '.log', '.out', '.tex']:
            try:
                os.remove(filename + ext)
            except:
                pass
```
which works great on windows. I can't test it on Unix as I have no unix system at work.

**Comment by JelteF** [comment]
Looks good, I don't think the exception should be a bit more specific. I'm not sure what error is raised when the file is not there, possibly IOerror or something, that way an unexpected exception is still recognized. But the handling itself is good, when the file is not there it also doesn't have to be removed.
If you can make a pull request I will merge it.

One more question, does the compiling really work on linux. Since the code uses the pdflatex command, or do you supply a different command for windows?

**Comment by winogradoff** [comment]
There is a whole latex for windows including pdflatex:
http://miktex.org/download

**Comment by JelteF** [comment]
It should be fixed by by https://github.com/JelteF/PyLaTeX/commit/af96fc00
Could one of you confirm that it now works on Windows?

**Comment by JelteF** [comment]
Oh, it seems I'm using a python 3 specific error. I will fix that, but for now could you guys check if it works with Python 3?

**Comment by winogradoff** [comment]
https://github.com/JelteF/PyLaTeX/commit/af96fc00
I can confirm it works.
(Windows 8.1, Pyhton 3.4.1)

**Comment by JelteF** [comment]
Great, then I will close the issue. Btw I have made a workaround for the error, so Python 2 should work again as well.

**Comment by jrast** [comment]
Can this issue be reopened? This bug exists again, see the comment I made for commit f6ffaa4

**Comment by JelteF** [comment]
I missed those when merging. It should be fixed now.
