### ISSUE TITLE
rm_tmp called even if clean=False in generate_pdf

### ISSUE THREAD

**Issue by fariza** [JelteF/PyLaTeX#63]
`rm_tmp` is called even if `Document.generate_pdf` is called with `clean=False`
Is this normal? if so, how do we compile several times to update cross references?

The problem are the graphics that are removed for the second call

**Comment by JelteF** [comment]
No, that shouldn't happen. That's probably a bug. I'm planning on rewriting the temp stuff by using the temporary file module in Python. Also, I plan on using the new lib called just "latex" to replace the latex compile method I hacked together since its way more robust and does run multiple times when needed.

**Comment by fariza** [comment]
For that kind of really small bugs, do you still  want a changelong entry?

**Comment by JelteF** [comment]
It's not that important, but yeah. It's always good to easily see what is
fixed in a new release.

**Comment by Rsullivan00** [comment]
For reference, I used the temporary file module in a side project that cloned this repo a few months ago.

I used it to just generate a unique filename, like:
```
f = tempfile.NamedTemporaryFile(prefix='blah_')
self.filename = f.name
f.close()
```
A lot of the Document code has changed since then, but my version is at https://github.com/Rsullivan00/transcript-to-latex/blob/master/pylatex/document.py.
