### ISSUE TITLE
Tikz integration

### ISSUE THREAD

**Issue by MisterSheik** [JelteF/PyLaTeX#68]
This is an excellent project.  I am currently generating latex using Python scripts for my work already.

Can I suggest that instead of generating tikz, we improve matplotlib so that it can generate comparable quality images with similar ease?  I am working on it here: https://github.com/MisterSheik/matplotlib

Best,

Neil

**Comment by MisterSheik** [comment]
(https://github.com/MisterSheik/matplotlib/tree/arrows)

**Comment by JelteF** [comment]
Hi Neil,

The Tikz plotting integration was added in one of the first versions, in its current state it can't really be used for anything more than the most basic of plots. I don't use it myself at all actually. Since v0.7.0 basic matplotlib integration has been added. I use that quite a bit myself now for my own assignments. I do think however that the matplotlib api is quite terrible, that is why I use seaborn as a wrapper around it most of the time. https://web.stanford.edu/~mwaskom/software/seaborn/

What is it exactly you need from me? Does pylatex need features for what you are currently trying to make?

**Comment by MisterSheik** [comment]
I just noticed that you were adding tikz integration and I think that it's a waste of time to try to generate tikz, which is then compiled by latex. It would be better to generate pdfs in matplotlib (or seaborn) and then tikzinclude them into latex.  If you're not working on further tikz integration and plotting in pylatex, then this doesn't matter to you.

**Comment by JelteF** [comment]
Ah ok, thanks. In that case I will close the issue. I do still use tikz when writing latex btw, as it is great for drawing of graphs or trees. I haven't felt the need however to include functionality for that in this library, since drawing those can't be automated most of the time in my experience.
