### ISSUE TITLE
What needs to be done for the next release?

### ISSUE THREAD

**Issue by rfilmyer** [JelteF/PyLaTeX#81]
Clearly a lot has been done since v0.8.0, and the current package/documentation is a lot different from what it was a few months ago.

What needs to be done before the next release can be pushed out?

**Comment by JelteF** [comment]
- [ ] First of all, all the TODO's in the comments should be handled. Mostly because they will be backwards incompatible and I want to release v1.0.0 next and after that not break backwards compatibility.

- [ ] Useful docstrings in every baseclass, since those are most important but the most important places for those would be the base classes. Since those are the most difficult to understand by themselves. 

- [ ] Numpy type docstrings everywhere instead of the unreadable sphinx docstrings.

- [ ] Add a class that is the floating table environment and remove the current Table class which is replaced by Tabular.

**Comment by JelteF** [comment]
I have made a milestone and added some issues to it. Please let me know if you are going to be working on one so we don't do double work. Closing this now.
